(()=>{
  const F=window.KumonAdminFields,$=id=>document.getElementById(id);
  let db=null,slides=[],media={},cloud={},selected=-1,dirty=false,started=false;
  const deep=v=>JSON.parse(JSON.stringify(v));
  function normalise(raw){if(!raw)return[];if(Array.isArray(raw))return raw.filter(Boolean);return Object.keys(raw).sort((a,b)=>Number(a)-Number(b)).map(k=>raw[k]).filter(Boolean)}
  function toast(msg,error=false){const t=$('toast');t.textContent=msg;t.className='toast show'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.className='toast',2600)}
  function setDirty(v=true){dirty=v;$('dirtyLabel').textContent=v?'Alterações ainda não salvas':'Tudo salvo no Firebase';$('saveStatus').textContent=v?'Alterações pendentes':'Sincronizado com Firebase'}
  function slideTitle(s){return F.labelOf(s)||'Slide sem título'}
  function renderList(){const root=$('slideList');root.innerHTML=slides.map((s,i)=>`<button type="button" class="slide-item ${i===selected?'active':''}" data-index="${i}"><span class="slide-index">${String(i+1).padStart(2,'0')}</span><span class="slide-copy"><strong>${F.esc(slideTitle(s))}</strong><span>${F.esc(F.types.find(x=>x[0]===s.type)?.[1]||s.type||'slide')}</span></span></button>`).join('');root.querySelectorAll('.slide-item').forEach(b=>b.onclick=()=>select(Number(b.dataset.index)))}
  function setOptional(type){const o=F.optional(type);document.querySelectorAll('.optional-field').forEach(x=>x.classList.toggle('hidden',!o[x.dataset.key]));$('mediaSection').classList.toggle('hidden',!F.needsMedia(type));$('addField').classList.toggle('hidden',['quote','end','media-full'].includes(type))}
  function currentMedia(s){return media[s.mediaId]||s.defaultMedia||''}
  function preview(url){const p=$('mediaPreview');if(!url){p.innerHTML='<span>Nenhuma mídia selecionada</span>';return}if(/youtube\.com|youtu\.be/i.test(url)){let id='';try{const u=new URL(url);id=u.hostname.includes('youtu.be')?u.pathname.slice(1):u.searchParams.get('v')||''}catch(e){}p.innerHTML=id?`<iframe src="https://www.youtube.com/embed/${F.esc(id)}" title="Prévia"></iframe>`:'<span>Link do YouTube</span>';return}if(/\.(mp4|webm|mov)(\?|$)/i.test(url)||/\/video\/upload\//i.test(url)){p.innerHTML=`<video src="${F.esc(url)}" controls muted playsinline></video>`;return}p.innerHTML=`<img src="${F.esc(url)}" alt="Prévia" onerror="this.parentElement.innerHTML='<span>Não foi possível visualizar esta mídia</span>'">`}
  function refreshJson(){if(selected<0)return;$('jsonEditor').value=JSON.stringify(slides[selected],null,2)}
  function renderEditor(){if(selected<0||!slides[selected]){$('emptyEditor').classList.remove('hidden');$('editorForm').classList.add('hidden');return}const s=slides[selected];$('emptyEditor').classList.add('hidden');$('editorForm').classList.remove('hidden');$('slideNumber').textContent=`SLIDE ${selected+1} DE ${slides.length}`;$('editorTitle').textContent=slideTitle(s);$('fieldType').innerHTML=F.typeOptions(s.type||'list');$('fieldType').value=s.type||'list';$('fieldIcon').innerHTML=F.iconOptions(s.icon||'fa-star');$('fieldIcon').value=s.icon||'fa-star';$('fieldTitle').value=F.titleOf(s);$('fieldSubtitle').value=s.type==='cover'?(s.sub||''):(s.subtitle||'');$('fieldAuthor').value=s.author||'';$('fieldContact').value=s.contact||'';$('fieldId').value=s.id||'';$('fieldMedia').value=currentMedia(s);setOptional(s.type);F.renderDynamic(s,$('dynamicFields'));preview(currentMedia(s));refreshJson();renderList()}
  function select(i){if(i<0||i>=slides.length)return;selected=i;renderEditor()}
  function syncBasic(mark=true){if(selected<0)return;const s=slides[selected];const title=$('fieldTitle').value;if(s.type==='cover'){s.t=title;s.sub=$('fieldSubtitle').value}else if(s.type==='quote'){s.text=title;s.author=$('fieldAuthor').value}else if(s.type==='end'){s.title=title;s.subtitle=$('fieldSubtitle').value;s.contact=$('fieldContact').value}else{s.title=title}s.icon=$('fieldIcon').value||s.icon||'fa-star';F.collect(s,$('dynamicFields'));if(F.needsMedia(s.type)){s.mediaId=s.mediaId||('media_'+s.id);const u=$('fieldMedia').value.trim();if(u)media[s.mediaId]=u;else delete media[s.mediaId]}refreshJson();renderList();$('editorTitle').textContent=slideTitle(s);if(mark)setDirty(true)}
  function removeDynamic(row){if(selected<0)return;const s=slides[selected];F.collect(s,$('dynamicFields'));const idx=Number(row.dataset.index);if(s.type==='cover')s.ext='';else if(['list','media-left','media-right'].includes(s.type))s.items.splice(idx,1);else if(s.type==='grid')s.grid.splice(idx,1);else if(s.type==='team')s.groups.splice(idx,1);else if(s.type==='table')s.rows.splice(idx,1);else if(s.type==='stats')s.stats.splice(idx,1);else if(s.type==='sophia'){if(row.hasAttribute('data-detail'))s.details.splice(idx,1);else s.name=''}F.renderDynamic(s,$('dynamicFields'));refreshJson();setDirty(true)}
  async function save(){if(selected>=0)syncBasic(false);$('saveStatus').textContent='Salvando...';try{await db.ref('kumon_config/presentation').update({slides,version:2,updatedAt:firebase.database.ServerValue.TIMESTAMP});await db.ref('kumon_config/settings/media').set(media);setDirty(false);toast('Apresentação salva e sincronizada.')}catch(e){console.error(e);$('saveStatus').textContent='Erro ao salvar';toast('Erro ao salvar: '+e.message,true)}}
  async function ensureSlides(){let v=normalise((await db.ref('kumon_config/presentation/slides').once('value')).val());if(v.length)return v;v=await window.LegacySlidesParser.load();await db.ref('kumon_config/presentation').update({slides:v,version:2,migratedAt:firebase.database.ServerValue.TIMESTAMP});return v}
  async function start(){if(started)return;started=true;try{firebase.initializeApp(window.KUMON_FIREBASE_CONFIG);db=firebase.database();db.ref('.info/connected').on('value',s=>$('saveStatus').textContent=s.val()?(dirty?'Alterações pendentes':'Conectado ao Firebase'):'Sem conexão');const settings=(await db.ref('kumon_config/settings').once('value')).val()||{};media=settings.media||{};cloud=settings.cloudinary||{};slides=await ensureSlides();const st=await db.ref('kumon_config/state/currentSlide').once('value');selected=Math.max(0,Math.min(slides.length-1,Number(st.val()||0)));renderList();renderEditor();setDirty(false)}catch(e){started=false;console.error(e);toast('Falha ao iniciar editor: '+e.message,true)}}
  $('loginForm').addEventListener('submit',e=>{e.preventDefault();if($('adminPin').value==='*177'){sessionStorage.setItem('kumonEditor','1');$('login').classList.add('hidden');start()}else{toast('PIN incorreto.',true);$('adminPin').select()}});
  if(sessionStorage.getItem('kumonEditor')==='1'){$('login').classList.add('hidden');start()}
  $('editorForm').addEventListener('submit',e=>{e.preventDefault();save()});
  ['fieldTitle','fieldSubtitle','fieldAuthor','fieldContact'].forEach(id=>$(id).addEventListener('input',()=>syncBasic(true)));
  $('fieldIcon').addEventListener('change',()=>syncBasic(true));
  $('fieldMedia').addEventListener('input',()=>{if(selected<0)return;const s=slides[selected];s.mediaId=s.mediaId||('media_'+s.id);const u=$('fieldMedia').value.trim();if(u)media[s.mediaId]=u;else delete media[s.mediaId];preview(u);setDirty(true)});
  $('fieldType').addEventListener('change',()=>{if(selected<0)return;syncBasic(false);slides[selected]=F.convert(slides[selected],$('fieldType').value);renderEditor();setDirty(true)});
  $('dynamicFields').addEventListener('input',()=>syncBasic(true));
  $('dynamicFields').addEventListener('change',()=>syncBasic(true));
  $('dynamicFields').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b)removeDynamic(b.closest('.dynamic-row'))});
  $('addField').onclick=()=>{if(selected<0)return;syncBasic(false);F.add(slides[selected]);F.renderDynamic(slides[selected],$('dynamicFields'));refreshJson();setDirty(true)};
  function createSlide(type){slides.push(F.fresh(type||'list'));selected=slides.length-1;renderEditor();setDirty(true);$('newSlideDialog')?.close();toast('Novo slide criado. Edite e salve para publicar.')}
  $('newSlide').onclick=()=>{const d=$('newSlideDialog'),c=$('newSlideChoices');if(d&&c){c.innerHTML=F.types.map(([v,l])=>`<button type="button" data-new-type="${v}"><strong>${F.esc(l)}</strong><span>${F.needsMedia(v)?'Aceita foto, vídeo ou YouTube':'Estrutura pronta para edição'}</span></button>`).join('');d.showModal()}else createSlide('list')};
  $('newSlideChoices')?.addEventListener('click',e=>{const b=e.target.closest('[data-new-type]');if(b)createSlide(b.dataset.newType)});
  $('newSlideCancel')?.addEventListener('click',()=> $('newSlideDialog')?.close());
  $('moveUp').onclick=()=>{if(selected<=0)return;syncBasic(false);[slides[selected-1],slides[selected]]=[slides[selected],slides[selected-1]];selected--;renderEditor();setDirty(true)};
  $('moveDown').onclick=()=>{if(selected<0||selected>=slides.length-1)return;syncBasic(false);[slides[selected+1],slides[selected]]=[slides[selected],slides[selected+1]];selected++;renderEditor();setDirty(true)};
  $('duplicateSlide').onclick=()=>{if(selected<0)return;syncBasic(false);const old=slides[selected],c=deep(old);c.id=F.newId('slide');if(c.type==='cover')c.t=(c.t||'Slide')+' (cópia)';else if(c.type==='quote')c.text=(c.text||'Frase')+' (cópia)';else c.title=(c.title||'Slide')+' (cópia)';if(c.mediaId){const oldMedia=c.mediaId;c.mediaId='media_'+c.id;if(media[oldMedia])media[c.mediaId]=media[oldMedia]}if(c.grid)c.grid.forEach(x=>x.id=F.newId('card'));slides.splice(selected+1,0,c);selected++;renderEditor();setDirty(true)};
  $('deleteSlide').onclick=()=>{if(selected<0||!confirm('Excluir este slide da apresentação?'))return;slides.splice(selected,1);selected=slides.length?Math.min(selected,slides.length-1):-1;renderList();renderEditor();setDirty(true)};
  $('clearMedia').onclick=()=>{if(selected<0)return;const s=slides[selected];if(s.mediaId)delete media[s.mediaId];delete s.defaultMedia;$('fieldMedia').value='';preview('');refreshJson();setDirty(true)};
  $('uploadMedia').onclick=()=>{if(selected<0)return;if(!window.cloudinary){toast('Cloudinary não carregou.',true);return}if(!cloud.cloudName||!cloud.preset){toast('Cloudinary ainda não está configurado.',true);return}const widget=cloudinary.createUploadWidget({cloudName:cloud.cloudName,uploadPreset:cloud.preset,sources:['local','url','camera'],multiple:false,resourceType:'auto'},(err,res)=>{if(err){console.warn(err);return}if(res?.event==='success'){const s=slides[selected];s.mediaId=s.mediaId||('media_'+s.id);media[s.mediaId]=res.info.secure_url;$('fieldMedia').value=res.info.secure_url;s.mediaType=res.info.resource_type==='video'?'video':'image';preview(res.info.secure_url);refreshJson();setDirty(true);toast('Mídia enviada. Clique em salvar para publicar.')}});widget.open()};
  $('applyJson').onclick=()=>{if(selected<0)return;try{const parsed=JSON.parse($('jsonEditor').value);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('JSON precisa representar um slide.');parsed.id=parsed.id||slides[selected].id;slides[selected]=parsed;renderEditor();setDirty(true);toast('JSON aplicado ao slide.')}catch(e){toast('JSON inválido: '+e.message,true)}};
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
})();
