window.LegacySlidesParser=(()=>{
  function Parser(src){this.s=src;this.i=0}
  Parser.prototype.skip=function(){while(this.i<this.s.length){if(/\s/.test(this.s[this.i])){this.i++;continue}if(this.s.startsWith('//',this.i)){this.i+=2;while(this.i<this.s.length&&this.s[this.i]!='\n')this.i++;continue}if(this.s.startsWith('/*',this.i)){const e=this.s.indexOf('*/',this.i+2);this.i=e<0?this.s.length:e+2;continue}break}}
  Parser.prototype.string=function(){const q=this.s[this.i++];let out='';while(this.i<this.s.length){let c=this.s[this.i++];if(c===q)return out;if(c==='\\'){const n=this.s[this.i++];const map={n:'\n',r:'\r',t:'\t',b:'\b',f:'\f'};if(n==='u'){const h=this.s.slice(this.i,this.i+4);this.i+=4;out+=String.fromCharCode(parseInt(h,16));continue}out+=map[n]??n;continue}out+=c}throw new Error('String não finalizada')}
  Parser.prototype.word=function(){const st=this.i;while(this.i<this.s.length&&/[A-Za-z0-9_$.-]/.test(this.s[this.i]))this.i++;const w=this.s.slice(st,this.i);if(w==='true')return true;if(w==='false')return false;if(w==='null')return null;if(/^[-+]?\d+(\.\d+)?$/.test(w))return Number(w);return w}
  Parser.prototype.value=function(){this.skip();const c=this.s[this.i];if(c==='"'||c==="'")return this.string();if(c==='[')return this.array();if(c==='{')return this.object();return this.word()}
  Parser.prototype.array=function(){const a=[];this.i++;for(;;){this.skip();if(this.s[this.i]===']'){this.i++;return a}a.push(this.value());this.skip();if(this.s[this.i]===','){this.i++;continue}if(this.s[this.i]===']'){this.i++;return a}throw new Error('Array inválido perto de '+this.i)}}
  Parser.prototype.object=function(){const o={};this.i++;for(;;){this.skip();if(this.s[this.i]==='}'){this.i++;return o}let k;if(this.s[this.i]==='"'||this.s[this.i]==="'")k=this.string();else{k=this.word()}this.skip();if(this.s[this.i]!==':')throw new Error('Objeto inválido perto de '+this.i);this.i++;o[k]=this.value();this.skip();if(this.s[this.i]===','){this.i++;continue}if(this.s[this.i]==='}'){this.i++;return o}throw new Error('Objeto inválido perto de '+this.i)}}
  function extract(html){const m=html.match(/(?:const|let)\s+slidesData\s*=\s*\[/);if(!m)throw new Error('slidesData não encontrado na versão anterior');const start=m.index+m[0].lastIndexOf('[');const p=new Parser(html.slice(start));const data=p.value();if(!Array.isArray(data)||!data.length)throw new Error('Base de slides vazia');return data}
  async function load(){const r=await fetch('index.html?source=legacy&ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Não foi possível carregar a apresentação anterior');return extract(await r.text())}
  return{extract,load}
})();
